### PR TITLE
Use `RCTComponentEvent` for React Native 0.60

### PR DESCRIPTION
**Pull request by robertying**
## Summary

React Native 0.60 removes some deprecated stuff -> https://github.com/facebook/react-native/commit/41343f6a7305cc82c412898139c46c01047f3399

## Impact

This will be a breaking change.

### CODE REVIEW

**Comment by iRoachie** [comment]
Thanks for sending this in. Let's wait until 0.60 launches

**Comment by robertying** [comment]
It landed!

**Comment by jfrolich** [comment]
Would be great to have this merged. BTW it looks like you missed an import @Robdel12. Fixed it in my fork https://github.com/jfrolich/react-native-tableview.

**Comment by iRoachie** [comment]
@robertying I'm guessing we'll have to put a notice saying that users using rn60+ should use 3.0.0?

**Comment by robertying** [comment]
@iRoachie that would be ideal! 👍

**Comment by iRoachie** [comment]
Can you apply the missing import from @jfrolich

**Comment by robertying** [comment]
There is another unrelated fix https://github.com/robertying/react-native-tableview/compare/rn60...jfrolich:rn60#diff-715cea92e50210a34208cfeaeebff984L358. Do you want it as well?

**Comment by iRoachie** [comment]
Just the import for now

**Comment by ntwigs** [comment]
How are we doing on the merge?

**Comment by iRoachie** [comment]
Thanks for sending this 💯

**Pull request merged**
