### PR TITLE
Font utils have been been moved to RCTFont in RN 0.33.

### PR DESCRIPTION
**Pull request by danielbraun**
Library doesn't compile under RN 0.33, this PR fixed it.

See RN commit https://github.com/facebook/react-native/commit/c5a44b7ca37511823b24e3a4e9bfda8c715a5e64

### CODE REVIEW

**Comment by roysG** [comment]
any update?

**Comment by aksonov** [comment]
done

**Comment by roysG** [comment]
What should i need to do to see the fix?

**Comment by aksonov** [comment]
Update to latest npm version?

**Comment by roysG** [comment]
@aksonov 
So if i understand you correctly, when i run npm install npm@latest -g, the problem for issue:
https://github.com/aksonov/react-native-tableview/issues/115

Will be fix for ios, right?

**Pull request merged**
