### PR TITLE
Accessory views

### PR DESCRIPTION
**Pull request by nickw**
@aksonov I'm hoping you can help me troubleshoot something with this PR.

I hooked up the `tableView:accessoryButtonTappedForRowWithIndexPath ` callback for when a user taps an accessory item. The [NSLog statement here](https://github.com/aksonov/react-native-tableview/commit/9d6885c08a5cc2428bd41faef7b9d5a179756ac9#diff-715cea92e50210a34208cfeaeebff984R462) is logging correctly on the Obj-C side.

However on the JS side [this console.log](https://github.com/aksonov/react-native-tableview/commit/9d6885c08a5cc2428bd41faef7b9d5a179756ac9#diff-168726dbe96b3ce427e7fedce31bb0bcR173) is not firing. I've tried changing the event name here `[_eventDispatcher sendInputEventWithName:@"accessoryPress" body:newValue];` to `onAccessoryPress` and `topAccessoryPress` but neither worked. 

I don't know much about the way RN events are propagated to the JS so I'm hoping you have some insight here?

### CODE REVIEW

**Comment by nyura123** [comment]
@nickw maybe `onAccessoryPress` needs to be added `customEventDirectTypes` like some of the other events (RNTableViewManager.m):

```
- (NSArray *)customDirectEventTypes
{
    return @[
             @"onWillDisplayCell",
             @"onEndDisplayingCell",
             @"onItemNotification"
             ];
}
```

**Comment by nickw** [comment]
@nyura123 ah I bet that's it - good catch! I'll give that a try…

**Comment by nickw** [comment]
Thanks @nyura123 that worked!

@aksonov this should be ready to merge. Let me know if you want to look it over first, otherwise I can merge for you.

**Comment by aksonov** [comment]
Looks good!

**Pull request merged**
