### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by iRoachie**
Massive cleanup and refractor of the project.

### Still to do 
- [x]  Finish update example
- [x] Props table to show available props 
- [x] Update readme with new example gifs and images to make features clearer
- [x] Finish update prop defaults and eslint 

### Maybe 
- [x] Typescript definitions

### CODE REVIEW

**Comment by iRoachie** [comment]
@aksonov You can publish the new version! Already merged to master and bumped package.json. The release notes are here https://github.com/aksonov/react-native-tableview/releases/tag/2.0.0

**Comment by iRoachie** [comment]
@aksonov You could also add me as one of the code owners, so I won't have to bug you to publish https://docs.npmjs.com/cli/owner

**Comment by aksonov** [comment]
Great job for 2.0! Unfortunately I’m traveling right now and don’t have pc, will be back Dec, 28

**Comment by iRoachie** [comment]
Cool man! Happy holidays

**Comment by plondon** [comment]
Thanks guys for your work. Could 2.0.0 be published?

**Comment by aksonov** [comment]
Done

**Comment by aksonov** [comment]
@iRoachie what is your username there? 
```
bash-3.2$ npm owner add iRoachie
npm ERR! owner mutate Error getting user data for iRoachie
```

**Comment by iRoachie** [comment]
it's lowercase on npm `iroachie`

**Comment by aksonov** [comment]
Done

**Pull request merged**
