### PR TITLE
Fixed out-of-date ReadMe on "Editable Complex Components"

### PR DESCRIPTION
**Pull request by dylancom**
ReadMe on using "Editable Complex Components" is out-of-date.
It provides an unnecessary step on importing RNAppGlobals.

See: https://github.com/aksonov/react-native-tableview/blob/master/RNTableView/RNAppGlobals.m

And a PR that already made the importing unnecessary (but docs weren't updated):
https://github.com/aksonov/react-native-tableview/pull/102

### CODE REVIEW

**Comment by iRoachie** [comment]
Can you make seperate PRs to do different things? Also do you have any docs on the RNAppGlobals? I'd love to read up on it

**Comment by dylancom** [comment]
@iRoachie https://github.com/aksonov/react-native-tableview/blob/master/RNTableView/RNAppGlobals.m here you can see it's outdated.

**Comment by iRoachie** [comment]
Oh i thought you meant something with react-native on their end

**Comment by dylancom** [comment]
@iRoachie Updated the PR to only contain the ReadMe update.

**Comment by dylancom** [comment]
@iRoachie Is this package still being maintained?

**Comment by iRoachie** [comment]
Thanks @dylancom. I really don't have enough time to maintain it. But I also am not the admin so I can't assign a new maintainer.

**Pull request merged**
