### PR TITLE
add Insert mode handling (UITableViewCellEditingStyleInsert)

### PR DESCRIPTION
**Pull request by damikdk**

### CODE REVIEW

**Comment by iRoachie** [comment]
Can you explain your intention by making this change?

**Comment by damikdk** [comment]
Of course. There is no way to handle pressing on plus sign (and row itself maybe) if tableViewCellEditingStyle == Insert, like here:

photo_2018-08-19_22-41-46

**Comment by damikdk** [comment]
Any update, guys? I think, it's important

@iRoachie

**Comment by iRoachie** [comment]
Sorry about the wait, how would I be able to test if this works? Can you set up a quick example that I can test. Just want to make sure I don't break existing funcitonality

**Comment by damikdk** [comment]
I added second TableView with ```tableViewCellEditingStyle={TableView.Consts.CellEditingStyle.Insert}``` to 'Example 6' screen. If it works, you will see [this](https://github.com/damikdk/react-native-tableview/blob/handling-Insert-1/example/src/screens/Example6.js#L44) alert.

Now you can just run example project from [my branch](https://github.com/damikdk/react-native-tableview/tree/handling-Insert-1). Is it enough? :)

**Comment by damikdk** [comment]
Sorry for annoying, but can I get some feedback on this PR? Thank you!

**Pull request merged**
