### PR TITLE
Fix for React.createClass

### PR DESCRIPTION
**Pull request by iRoachie**
React 0.15.5 deprecated `React.createClass` and will be removed completely in a newer version of react. Since react-native@0.45, this now shows as an error when the apps are running. https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings

The React team has provided a drop-in replacement for `React.createClass` as a separate library called "create-react-class".

This PR replaces `React.createClass` with `createReactClass`

### CODE REVIEW

**Comment by aksonov** [comment]
Please check latest master now.

**Comment by iRoachie** [comment]
@aksonov Thanks for merging other PRs! If you need a maintainer let me know. Been using my fork https://github.com/iRoachie/react-native-tableview with fixes for react-native@0.50

**Comment by aksonov** [comment]
Yes, I really need maintainer for this component because I don't use it and don't have time to support right now

**Comment by iRoachie** [comment]
No problem, understood. I'm available

**Comment by aksonov** [comment]
The invitation was sent.

**Comment by iRoachie** [comment]
Accepted. Would you like me to handle the publishing to npm as well?

**Comment by aksonov** [comment]
I can publish, just let me know when.

**Comment by iRoachie** [comment]
Cool np 👍🏼

**Pull request closed without merging**
