### PR TITLE
add UITableViewCellSeparatorStyle support

### PR DESCRIPTION
**Pull request by ioje**
now v can set the property separatorStyle when create the TableView, which support 3 native styles.

### CODE REVIEW

**Comment by cancan101** [comment]
It looks like some files got merged that should not have.

**Comment by ioje** [comment]
@cancan101 sorry, it's my faults :-p

**Comment by cancan101** [comment]
@ioje see: #58

**Comment by cancan101** [comment]
I think this entire directory should be excluded from git: https://github.com/aksonov/react-native-tableview/tree/master/RNTableView.xcodeproj/xcuserdata

**Pull request merged**
