### PR TITLE
Added option for no tableViewStyle

### PR DESCRIPTION
**Pull request by gabrielbull**
Sometimes, we might want to have no tableViewStyle

### CODE REVIEW

**Comment by gabrielbull** [comment]
You are allowed to not have a UiTableViewStyle, which is what I am doing here.

**Comment by iRoachie** [comment]
Passing in `nil` as the value resolves to UITableViewStylePlain.

screen shot 2018-06-19 at 10 38 04 pm

screen shot 2018-06-19 at 10 37 32 pm

**Comment by gabrielbull** [comment]
Yeah, I said basically the same 🤣. The PR works fine but if you want me to re-write it a different way I'm happy to oblige.

**Comment by iRoachie** [comment]
It's okay, there's no need for a PR then. The user would choose either plain or grouped. I see you have other PRs but it's kinda late so i'll check them another time. Thanks for the interest!

**Comment by gabrielbull** [comment]
Can we remove the default to Plain then? otherwise it is not possible but to have no tableCellStyle.

https://github.com/aksonov/react-native-tableview/blob/8f184772712a7439bb4170fb6736cfd093a7f290/src/TableView.js#L104

**Comment by iRoachie** [comment]
Not really understanding, by default it has to be plain or grouped. 

tableCellStyle being set to nil will have the same behaviour as defaulting to `default`. 
https://developer.apple.com/documentation/uikit/uitableviewcell/cellstyle

**Comment by gabrielbull** [comment]
You are talking about UITableView __Cell__. I am talking about UITableView which has no style by default.

**Pull request closed without merging**
